### ISSUE TITLE
Consider reformatting solution files as txt instead of markdown

### ISSUE THREAD

**Issue by bitschmidty** [bitcoinops/taproot-workshop#112]
Is anyone opening the solution files as formatted markdown? Seems to just impair my ability to copy paste from the solution file, personally.

**Comment by jnewbery** [comment]
I think we should reformat these as notebooks, so each solution is in its own cell.

**Comment by jnewbery** [comment]
I have a branch for this, queued up behind #111

**Comment by jnewbery** [comment]
PR at #117
