### ISSUE TITLE
Changes to taproot descriptors

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/taproot-workshop#123]
A few observations on things that confused workshop particiapnts:

- `OP_RIPEMD160` is an unusual opcode. I think `OP_HASH160` is more commonly used (eg lightning HTLCs use `OP_HASH160`). We should replace `OP_RIPEMD160` with `OP_HASH160` in the notebooks.
- `pkhash` is confusing since it sounds very similar to the 'pubkey hash' in P2PKH. Consider renaming it, perhaps to `pk_and_hash` or `pk_with_hash`?
- `hasholder` and `pkhasholder` are slightly confusing since most people seem to parse them as _has holder_ and _pk has holder_.

**Comment by jachiang** [comment]
Agree with above points. Some ideas:
- pk_delay (nsequence delay)
- pk_time (timelock)
- ...pk_hash_delay

**Comment by jnewbery** [comment]
I like `pk_hashlock` and `pk_delay`. (`pk_time` seems fine but isn't relevant to these notebooks).

**Comment by jachiang** [comment]
@jnewbery, just to clarify before I make the changes in the library and chapters. 
Our tapscript descriptor tags would be as follows (with hash-locks using `OP_HASH160`), right?

* `pk`
* `pk_delay`
* `pk_hashlock`
* `pk_hashlock_delay`
* `csa`
* `csa_delay`
* `csa_hashlock`
* `csa_hashlock_delay`

**Comment by jnewbery** [comment]
> Our tapscript descriptor tags would be as follows

Yes, that looks good to me.

**Comment by jachiang** [comment]
I will work on this first thing tomorrow, unless you already are @jnewbery?

**Comment by jnewbery** [comment]
> I will work on this first thing tomorrow, unless you already are @jnewbery?

Thanks! I'm not working on it.

**Comment by jnewbery** [comment]
Fixed in #138
