### ISSUE TITLE
"JSONRPCException: Method not found (-32601)" for node.getbalance()

### ISSUE THREAD

**Issue by codeShark149** [bitcoinops/taproot-workshop#133]
Chapter 2.0: Taproot Introduction
Example 2.0.2 

`balance = node.getbalance()` is giving "Method not found" error.
 
`node.getnetworkinfo()` is returning valid version data from node.

Any suggestion on what might be going wrong? 

Thanks and regards.

**Comment by jnewbery** [comment]
For anyone else who comes across this issue:

`node.getbalance()` requires a wallet. This was failing for you because the wallet was disabled.
