### ISSUE TITLE
s/leafs/leaves

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/taproot-workshop#135]
There are lots of instances of 'leafs' in these notebooks. They should be corrected to 'leaves'.

Same for 'tapleafs' -> 'tapleaves'

**Comment by bitschmidty** [comment]
Added a checklist here as some images are involved that @jachiang might be quicker to update:

- [ ] Notebooks content @bitschmidty 
- [ ] degrading_multisig0 image @jachiang 
- [ ] musig_intro_1 image @jachiang 
- [ ] taptree2 image @jachiang 
- [ ] taptree3 images @jachiang

**Comment by jachiang** [comment]
Hi @bitschmidty,
I don't see any "leafs" in degrading_multisig0 or musig_intro1? What am I missing?

**Comment by bitschmidty** [comment]
@jachiang Just going by the svg source files:
https://github.com/bitcoinops/taproot-workshop/pull/149/files

Perhaps there is text that is in the svg but doesn’t "show" in the image?
