### ISSUE TITLE
Test on windows

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/taproot-workshop#14]
Need to make sure that these notebooks work on windows. The underlying TestFramework works on windows, so as long as we make all of the TestWrapper and notebook code platform portable, then we should be ok.

- [ ] https://github.com/bitcoinops/taproot-workshop/pull/7/files/24446a69e91ffcbfd3d8202b37e4b58996effd31#diff-44e5bd8797cd0620ff134003c9d3d02d (how to kill orphan bitcoind processes on windows)

@bitschmidty is going to poll attendees to see if any of them will use windows.

**Comment by bitschmidty** [comment]
I have not gotten any feedback from people about a Windows machine being used at the workshop. Given our time constraints, Im leaning towards putting this off unless we hear otherwise.

**Comment by jnewbery** [comment]
> Im leaning towards putting this off unless we hear otherwise.

ACK
