### ISSUE TITLE
Colab branch is outdated

### ISSUE THREAD

**Issue by mmilata** [bitcoinops/taproot-workshop#172]
E.g. in 1.1([master](https://github.com/bitcoinops/taproot-workshop/blob/master/1.1-schnorr-signatures.ipynb), [Colab](https://github.com/bitcoinops/taproot-workshop/blob/Colab/1.1-schnorr-signatures.ipynb)) the Colab branch has outdated (pre-BIP maybe?) definition of Schnorr signing, but uses `test_framework` from master. Due to this mismatch the exercises are unsolvable.

Is there anything else than rebasing Colab on top of master needed?

**Comment by jnewbery** [comment]
Fixed in #173
