### ISSUE TITLE
Challenge Tags Enum

### ISSUE THREAD

**Issue by amovfx** [bitcoinops/taproot-workshop#180]
I think the note books could benefit from a challenge tags enum to avoid small typos that are hard to spot.

I can add these into a pr request if you guys think its a good idea.

**Comment by Xekyo** [comment]
Hi amovfx, could you elaborate what your idea is? I’m not sure I understand what you are suggesting.

**Comment by bitschmidty** [comment]
Going to close for now since it is unclear what the issue is.
