### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dspicher** [bitcoinops/taproot-workshop#183]
There is no license in this repository. Under what license is the content published?

**Comment by casey-bowman** [comment]
I'd like to second this question. I wrote an email yesterday asking if this workshop is open source and, if so, which license it would be using.

**Comment by casey-bowman** [comment]
I'd like to use it and perhaps update it and modify it as needed, perhaps using some material I've developed for working with bitcoin in Jupyter notebook in conjunction with Base58's Taproot Intensive class and my own work on making prototype transactions for a project I'm working on. I'll continue to keep my work separate if there's no response, but I'd like to spend time delving into this workshop and tweaking it if it is open source. It seems like it was created in that spirit, but I just wanted to be sure.

**Comment by bitschmidty** [comment]
@dspicher @casey-bowman we have added an MIT License to the repo

**Comment by dspicher** [comment]
Thanks!
