### ISSUE TITLE
How to represent a a zero witness element in k-of-n multisig transaction witness?

### ISSUE THREAD

**Issue by jainanubha** [bitcoinops/taproot-workshop#186]
In case of a k-of-n checksigadd multisignature tapscript, Tapscript is [pk0] [CHECKSIG] [PK1] [CHECKSIGADD] [PK2] [CHECKSIGADD] [2] [NUMEQUAL] and following are the possible spending witnesses:
[sig2] [sig1] []
[sig2] [] [sig0]
[] [sig1] [sig0]
How is the empty signature in witness stack specified when creating the spending txn?

**Comment by bitschmidty** [comment]
@jainanubha thanks for reaching out here but I dont think this is the right place for this question, if Im not mistaken.

You might consider asking something similar on the [Bitcoin Stack Exchange](https://bitcoin.stackexchange.com/)
