### ISSUE TITLE
The Bitcoin testnode is using legacy wallets which are not supported by default anymore

### ISSUE THREAD

**Issue by mccwdev** [bitcoinops/taproot-workshop#187]
Using Bitcoin core v25.1, build on ubuntu with default parameters.

Running example Example 2.0.2 results in this error:

```python
File ~/code/taproot-workshop/test_framework/authproxy.py:141, in AuthServiceProxy.__call__(self, *args, **argsn)
    139 response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))
    140 if response['error'] is not None:
--> 141     raise JSONRPCException(response['error'], status)
    142 elif 'result' not in response:
    143     raise JSONRPCException({
    144         'code': -343, 'message': 'missing JSON-RPC result'}, status)

JSONRPCException: Compiled without bdb support (required for legacy wallets) (-4)
```

Was able to fix it following this instructions:
https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#berkeley-db

But maybe you can avoid using legacy wallets or update the installation instructions.

**Comment by bitschmidty** [comment]
@mccwdev Thanks for the heads up. Since you were able to get it working with a fix, care to PR with the updated instructions?

**Comment by mccwdev** [comment]
Yes, see PR #189
