### ISSUE TITLE
image updates for chapter 0.2

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/taproot-workshop#24]
@jachiang please address the following:

- https://github.com/bitcoinops/taproot-workshop/pull/13#discussion_r320789551
- https://github.com/bitcoinops/taproot-workshop/pull/13#discussion_r324253922
- https://github.com/bitcoinops/taproot-workshop/pull/13#discussion_r324481755

**Comment by jachiang** [comment]
Fixes addressed in [#25](https://github.com/bitcoinops/taproot-workshop/pull/25#issue-318161566).
