### ISSUE TITLE
Requested fixes to images/schnorr0.jpg

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/taproot-workshop#29]
- rename diagram to 'Schnorr Signing and Verification'
- What does 'k blinds x' mean?
- Don't capitalize the labels (eg 'Nonce Point')

@jachiang

**Comment by jachiang** [comment]
'k blinds x' means x cannot be inferred from repeated signing due to blinding randomness provided by k.  I've removed it, it's doesn't need to be in the overview graphic, and may add confusion.

**Comment by jachiang** [comment]
Fixed in [#38](https://github.com/bitcoinops/taproot-workshop/pull/38#issue-319204213).
