### ISSUE TITLE
Link to optech branch is broken in BitcoinEdge branch

### ISSUE THREAD

**Issue by ysangkok** [bitcoinops/taproot-workshop#42]
The readme includes a link to https://github.com/bitcoinops/bitcoin/releases/tag/v0.1 . I believe this should point to the branch instead, since that tag doesn't seem to exist any more.

Only an issue on this branch: https://github.com/bitcoinops/taproot-workshop/tree/BitcoinEdge

**Comment by jachiang** [comment]
Thanks @ysangkok. It should point to this:
https://github.com/bitcoinops/bitcoin/releases/tag/Taproot_V0.1.2

**Comment by jachiang** [comment]
[Link](https://github.com/bitcoinops/taproot-workshop/tree/BitcoinEdge#build-a-taproot-supporting-bitcoind) updated.

**Comment by jnewbery** [comment]
Sorry - my bad. I changed the name of the tag.
