### ISSUE TITLE
MuSig needs 3 rounds

### ISSUE THREAD

**Issue by sipa** [bitcoinops/taproot-workshop#45]
Unsure if the goal of these worksheets is demonstrating how to build a secure protocol, but when using MuSig between multiple participants, you *must* have 3 rounds at signing time:
* In round one, the hashes of the public nonces are exchanged (so that every participant knows the nonce hashes of everyone else)
* In round two, the public nonces themselves are exchanged.
* In round three, the partial signatures are combined.

It is insecure when skipping the first round (which may seem redundant).

**Comment by jachiang** [comment]
Hi @sipa - many thanks for reviewing the material.

Are you referring to Chapter 1.2? Our intention in 1.2 was to make clear that there are 3 rounds, including the first public nonce commitment round to ensure nonces are indeed generated randomly and independently.

Did we omit this elsewhere?

**Comment by sipa** [comment]
I'm sorry, it seems I misread. The diagram was a bit confusing as I only saw two phases, but those seem distinct from the rounds.

My bad! I'll review in more detail soon.
