### ISSUE TITLE
Requested changes to the huffman encoding optional chapter

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/taproot-workshop#54]
From @bitschmidty review comment (https://github.com/bitcoinops/taproot-workshop/pull/19#discussion_r326719875):

This graphic isn't clear to me. Perhaps because I am dense. Heres a few suggestions:

- Is the last graphic intentionally missing the weight at the root? I would have expected 7
- Perhaps keep in the 2 in the second graphic and the 2,4 in the 3 graphic
- I don't understand "connect node pair with lowest weight total" and how it relates to the graphic

**Comment by jachiang** [comment]
I will add revisit and clarify the points above in the optional huffman tree encoding section (chapter 2.5).
