### ISSUE TITLE
Updates to chapter 2.2

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/taproot-workshop#93]
A few thoughts on chapter 2.2:

- [ ] exercise 2.2.2 should have more `prints()`. In general, we should add as many prints as we can to the exercises so they're more interactive and give more feedback to the users. @bitschmidty 
- [ ] exercises 2.2.3 and 2.2.4 should unseal the commitment (ie the signer proves that they've committed to `x`) so it's obvious why being able to change the commitment is bad. This ties into https://github.com/bitcoinops/taproot-workshop/issues/86. Perhaps the commitment should be something like "Pay 0.1 BTC to Optech" and the fake commitment changes that to "Pay 10BTC to Optech". @jachiang

**Comment by bitschmidty** [comment]
@jachiang I split these up for us. Perhaps you can help with the second suggestion?
